### ISSUE TITLE
firebase performance 라이브러리와 함께 사용했을 때 D8 빌드에러가 발생합니다.

### ISSUE THREAD

**Issue by bsscco** [KakaoAd/kakao-ad-android#2]
안녕하세요! 우리앱에 KakaAd SDK를 추가한 후 빌드에러가 발생하고 있습니다!
firebase perfomance 라이브러리의 case-sensitive 관련 버그라고 합니다!
`com.kakao.ad.a.L` 과 `com.kakao.ad.a.l`의 차이를 인식하지 못하고 빌드에러를 내고 있어요!

**다음 링크를 참고해주세요!**
https://stackoverflow.com/questions/56574811/dexarchivebuilderexception-with-firebase-performance-monitoring-library-r8-fail

![image](https://user-images.githubusercontent.com/11385606/63565543-5d2c3f00-c5a4-11e9-9012-de4fbc466c87.png)

라이브러리 프로가드파일에 `-dontusemixedcaseclassnames` 를 추가하면 해결할 수 있다고 합니다! 부탁드려요!

**Comment by Unbalance09** [comment]
안녕하세요. 

해당 이슈는 [R8 Shrinker](https://android-developers.googleblog.com/2018/11/r8-new-code-shrinker-from-google-is.html)에서 이미 존재하는 `-dontusemixedcaseclassnames` 룰을 
무시해서 발생하는 오류임을 확인하였습니다. 

문제가 해결된 버전을 배포 후 다시 코멘트 남기도록 하겠습니다.

제보 감사드립니다.

**관련 이슈 정보:**  
https://issuetracker.google.com/issues/129493704

**Comment by Unbalance09** [comment]
안녕하세요.
해당 이슈를 수정한 `0.3.5` 버전을 배포하였습니다.
문제가 여전히 발생하실 경우, 다시 피드백 부탁드립니다.
감사합니다.
