### ISSUE TITLE
커스텀 이벤트 및 커스텀 파라미터를 추가할 순 없나요?

### ISSUE THREAD

**Issue by khkong** [KakaoAd/kakao-ad-android#3]
데이터 형식이 맞지 않기도 하고, 별도로 넣고 싶은 정보가 있어서요.

**Comment by Unbalance09** [comment]
@khkong 
안녕하세요 
기획 이슈로 판단되여 기획 답변을 전달드립니다.

현재는 커스텀 이벤트를 지원하지 않고 있습니다. 
다만 "태그" 라는 기능을 지원하고 있어,
카카오모먼트 내의 픽셀&SDK 관리하는 화면 내에서 "태그"를 발급하신 뒤,
해당 "태그"를 사용하셔서 이벤트 하위에 추가 분류를 하실 수 있습니다.

감사합니다.
