### ISSUE TITLE
앱실행 로깅 최초수집 시점 관련

### ISSUE THREAD

**Issue by khkong** [KakaoAd/kakao-ad-android#4]
앱설치 로깅 -> aos, ios 모두 앱 설치 후 첫 실행시 수집
앱실행 로깅 -> ios는 첫 실행부터 수집, aos는 두 번째 실행 부터 수집

어느게 맞고 틀리고를 떠나 둘이 싱크가 안맞는게 문제인데요.
앱설치와 앱실행 로깅은 카카오에서 자동수집되는 로그여서, 저희가 컨트롤 할 수 없는 부분이라 어쩔 수 없는 상황입니다.
수정 부탁드립니다.

**Comment by Unbalance09** [comment]
@khkong 
안녕하세요 의견 감사합니다.

다음 버전(0.3.7 이후 버전)에 해당 요청 사항 반영하여 
Android SDK에서도 첫 실행부터 앱 실행 이벤트 처리하도록 하겠습니다.

감사합니다.

**Comment by Unbalance09** [comment]
@khkong 
안녕하세요 
해당 수정사항이 적용된 0.3.8 버전 배포되었습니다.
감사합니다.
