### ISSUE TITLE
안녕하세요. 질문이 있습니다.

### ISSUE THREAD

**Issue by dev-tryit** [KakaoAd/kakao-ad-android#9]
안녕하세요. 질문이 있습니다.

수동 수집 항목들은 제가 코딩을 한다면,
카카오 광고로만 들어온 유저들만, 자동으로 집계가 되나요?
아니면, 네이버 광고로 들어왔는지 카카오 광고로 들어왔는지 구분해서 수집해야 하나요?

**Comment by kyungw00k** [comment]
안녕하세요  @dev-tryit 

수집항목에 대한 부분만 작업해주시면 됩니다.
유입 경로는 내부적으로 추정 하고 있습니다.
다만, 유입경로를 주요하게 보지는 않고 참고 지표 정도로만 해석하고 있습니다.
